version: "3.3"

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: howto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      # - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3308:3308
    # restart: always
volumes:
  db:
    driver: local
