// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Image       string
	Item        string
	User        string
	UserAddress string
	UserCart    string
	UserOrder   string
}{
	Image:       "image",
	Item:        "item",
	User:        "user",
	UserAddress: "user_address",
	UserCart:    "user_cart",
	UserOrder:   "user_order",
}
