// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserOrder is an object representing the database table.
type UserOrder struct {
	ID           uint        `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID       uint        `boil:"user_id" json:"userID" toml:"userID" yaml:"userID"`
	AddressID    uint        `boil:"address_id" json:"addressID" toml:"addressID" yaml:"addressID"`
	Total        int         `boil:"total" json:"total" toml:"total" yaml:"total"`
	Payment      string      `boil:"payment" json:"payment" toml:"payment" yaml:"payment"`
	Status       string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	ShippingInfo null.String `boil:"shipping_info" json:"shippingInfo,omitempty" toml:"shippingInfo" yaml:"shippingInfo,omitempty"`
	DeliveredAt  null.Time   `boil:"delivered_at" json:"deliveredAt,omitempty" toml:"deliveredAt" yaml:"deliveredAt,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"createdAt,omitempty" toml:"createdAt" yaml:"createdAt,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updatedAt,omitempty" toml:"updatedAt" yaml:"updatedAt,omitempty"`
	DeletedAt    null.Time   `boil:"deleted_at" json:"deletedAt,omitempty" toml:"deletedAt" yaml:"deletedAt,omitempty"`

	R *userOrderR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userOrderL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserOrderColumns = struct {
	ID           string
	UserID       string
	AddressID    string
	Total        string
	Payment      string
	Status       string
	ShippingInfo string
	DeliveredAt  string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    string
}{
	ID:           "id",
	UserID:       "user_id",
	AddressID:    "address_id",
	Total:        "total",
	Payment:      "payment",
	Status:       "status",
	ShippingInfo: "shipping_info",
	DeliveredAt:  "delivered_at",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// Generated where

var UserOrderWhere = struct {
	ID           whereHelperuint
	UserID       whereHelperuint
	AddressID    whereHelperuint
	Total        whereHelperint
	Payment      whereHelperstring
	Status       whereHelperstring
	ShippingInfo whereHelpernull_String
	DeliveredAt  whereHelpernull_Time
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
	DeletedAt    whereHelpernull_Time
}{
	ID:           whereHelperuint{field: "`user_order`.`id`"},
	UserID:       whereHelperuint{field: "`user_order`.`user_id`"},
	AddressID:    whereHelperuint{field: "`user_order`.`address_id`"},
	Total:        whereHelperint{field: "`user_order`.`total`"},
	Payment:      whereHelperstring{field: "`user_order`.`payment`"},
	Status:       whereHelperstring{field: "`user_order`.`status`"},
	ShippingInfo: whereHelpernull_String{field: "`user_order`.`shipping_info`"},
	DeliveredAt:  whereHelpernull_Time{field: "`user_order`.`delivered_at`"},
	CreatedAt:    whereHelpernull_Time{field: "`user_order`.`created_at`"},
	UpdatedAt:    whereHelpernull_Time{field: "`user_order`.`updated_at`"},
	DeletedAt:    whereHelpernull_Time{field: "`user_order`.`deleted_at`"},
}

// UserOrderRels is where relationship names are stored.
var UserOrderRels = struct {
	User    string
	Address string
}{
	User:    "User",
	Address: "Address",
}

// userOrderR is where relationships are stored.
type userOrderR struct {
	User    *User        `boil:"User" json:"User" toml:"User" yaml:"User"`
	Address *UserAddress `boil:"Address" json:"Address" toml:"Address" yaml:"Address"`
}

// NewStruct creates a new relationship struct
func (*userOrderR) NewStruct() *userOrderR {
	return &userOrderR{}
}

// userOrderL is where Load methods for each relationship are stored.
type userOrderL struct{}

var (
	userOrderAllColumns            = []string{"id", "user_id", "address_id", "total", "payment", "status", "shipping_info", "delivered_at", "created_at", "updated_at", "deleted_at"}
	userOrderColumnsWithoutDefault = []string{"user_id", "address_id", "total", "payment", "status", "shipping_info", "delivered_at", "updated_at", "deleted_at"}
	userOrderColumnsWithDefault    = []string{"id", "created_at"}
	userOrderPrimaryKeyColumns     = []string{"id"}
)

type (
	// UserOrderSlice is an alias for a slice of pointers to UserOrder.
	// This should generally be used opposed to []UserOrder.
	UserOrderSlice []*UserOrder
	// UserOrderHook is the signature for custom UserOrder hook methods
	UserOrderHook func(context.Context, boil.ContextExecutor, *UserOrder) error

	userOrderQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userOrderType                 = reflect.TypeOf(&UserOrder{})
	userOrderMapping              = queries.MakeStructMapping(userOrderType)
	userOrderPrimaryKeyMapping, _ = queries.BindMapping(userOrderType, userOrderMapping, userOrderPrimaryKeyColumns)
	userOrderInsertCacheMut       sync.RWMutex
	userOrderInsertCache          = make(map[string]insertCache)
	userOrderUpdateCacheMut       sync.RWMutex
	userOrderUpdateCache          = make(map[string]updateCache)
	userOrderUpsertCacheMut       sync.RWMutex
	userOrderUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userOrderBeforeInsertHooks []UserOrderHook
var userOrderBeforeUpdateHooks []UserOrderHook
var userOrderBeforeDeleteHooks []UserOrderHook
var userOrderBeforeUpsertHooks []UserOrderHook

var userOrderAfterInsertHooks []UserOrderHook
var userOrderAfterSelectHooks []UserOrderHook
var userOrderAfterUpdateHooks []UserOrderHook
var userOrderAfterDeleteHooks []UserOrderHook
var userOrderAfterUpsertHooks []UserOrderHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserOrder) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserOrder) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserOrder) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserOrder) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserOrder) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserOrder) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserOrder) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserOrder) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserOrder) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userOrderAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserOrderHook registers your hook function for all future operations.
func AddUserOrderHook(hookPoint boil.HookPoint, userOrderHook UserOrderHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userOrderBeforeInsertHooks = append(userOrderBeforeInsertHooks, userOrderHook)
	case boil.BeforeUpdateHook:
		userOrderBeforeUpdateHooks = append(userOrderBeforeUpdateHooks, userOrderHook)
	case boil.BeforeDeleteHook:
		userOrderBeforeDeleteHooks = append(userOrderBeforeDeleteHooks, userOrderHook)
	case boil.BeforeUpsertHook:
		userOrderBeforeUpsertHooks = append(userOrderBeforeUpsertHooks, userOrderHook)
	case boil.AfterInsertHook:
		userOrderAfterInsertHooks = append(userOrderAfterInsertHooks, userOrderHook)
	case boil.AfterSelectHook:
		userOrderAfterSelectHooks = append(userOrderAfterSelectHooks, userOrderHook)
	case boil.AfterUpdateHook:
		userOrderAfterUpdateHooks = append(userOrderAfterUpdateHooks, userOrderHook)
	case boil.AfterDeleteHook:
		userOrderAfterDeleteHooks = append(userOrderAfterDeleteHooks, userOrderHook)
	case boil.AfterUpsertHook:
		userOrderAfterUpsertHooks = append(userOrderAfterUpsertHooks, userOrderHook)
	}
}

// OneG returns a single userOrder record from the query using the global executor.
func (q userOrderQuery) OneG(ctx context.Context) (*UserOrder, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single userOrder record from the query.
func (q userOrderQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserOrder, error) {
	o := &UserOrder{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_order")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all UserOrder records from the query using the global executor.
func (q userOrderQuery) AllG(ctx context.Context) (UserOrderSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all UserOrder records from the query.
func (q userOrderQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserOrderSlice, error) {
	var o []*UserOrder

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserOrder slice")
	}

	if len(userOrderAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all UserOrder records in the query, and panics on error.
func (q userOrderQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all UserOrder records in the query.
func (q userOrderQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_order rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q userOrderQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q userOrderQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_order exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserOrder) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "`user`")

	return query
}

// Address pointed to by the foreign key.
func (o *UserOrder) Address(mods ...qm.QueryMod) userAddressQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.AddressID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := UserAddresses(queryMods...)
	queries.SetFrom(query.Query, "`user_address`")

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userOrderL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserOrder interface{}, mods queries.Applicator) error {
	var slice []*UserOrder
	var object *UserOrder

	if singular {
		object = maybeUserOrder.(*UserOrder)
	} else {
		slice = *maybeUserOrder.(*[]*UserOrder)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userOrderR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userOrderR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, args...),
		qmhelper.WhereIsNull(`user.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userOrderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// LoadAddress allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userOrderL) LoadAddress(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserOrder interface{}, mods queries.Applicator) error {
	var slice []*UserOrder
	var object *UserOrder

	if singular {
		object = maybeUserOrder.(*UserOrder)
	} else {
		slice = *maybeUserOrder.(*[]*UserOrder)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userOrderR{}
		}
		args = append(args, object.AddressID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userOrderR{}
			}

			for _, a := range args {
				if a == obj.AddressID {
					continue Outer
				}
			}

			args = append(args, obj.AddressID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user_address`),
		qm.WhereIn(`user_address.id in ?`, args...),
		qmhelper.WhereIsNull(`user_address.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load UserAddress")
	}

	var resultSlice []*UserAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice UserAddress")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user_address")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user_address")
	}

	if len(userOrderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Address = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AddressID == foreign.ID {
				local.R.Address = foreign
				break
			}
		}
	}

	return nil
}

// SetUserG of the userOrder to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserOrders.
// Uses the global database handle.
func (o *UserOrder) SetUserG(ctx context.Context, insert bool, related *User) error {
	return o.SetUser(ctx, boil.GetContextDB(), insert, related)
}

// SetUser of the userOrder to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserOrders.
func (o *UserOrder) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `user_order` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, userOrderPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userOrderR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserOrders: UserOrderSlice{o},
		}
	} else {
		related.R.UserOrders = append(related.R.UserOrders, o)
	}

	return nil
}

// SetAddressG of the userOrder to the related item.
// Sets o.R.Address to related.
// Adds o to related.R.AddressUserOrders.
// Uses the global database handle.
func (o *UserOrder) SetAddressG(ctx context.Context, insert bool, related *UserAddress) error {
	return o.SetAddress(ctx, boil.GetContextDB(), insert, related)
}

// SetAddress of the userOrder to the related item.
// Sets o.R.Address to related.
// Adds o to related.R.AddressUserOrders.
func (o *UserOrder) SetAddress(ctx context.Context, exec boil.ContextExecutor, insert bool, related *UserAddress) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `user_order` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"address_id"}),
		strmangle.WhereClause("`", "`", 0, userOrderPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AddressID = related.ID
	if o.R == nil {
		o.R = &userOrderR{
			Address: related,
		}
	} else {
		o.R.Address = related
	}

	if related.R == nil {
		related.R = &userAddressR{
			AddressUserOrders: UserOrderSlice{o},
		}
	} else {
		related.R.AddressUserOrders = append(related.R.AddressUserOrders, o)
	}

	return nil
}

// UserOrders retrieves all the records using an executor.
func UserOrders(mods ...qm.QueryMod) userOrderQuery {
	mods = append(mods, qm.From("`user_order`"), qmhelper.WhereIsNull("`user_order`.`deleted_at`"))
	return userOrderQuery{NewQuery(mods...)}
}

// FindUserOrderG retrieves a single record by ID.
func FindUserOrderG(ctx context.Context, iD uint, selectCols ...string) (*UserOrder, error) {
	return FindUserOrder(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindUserOrder retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserOrder(ctx context.Context, exec boil.ContextExecutor, iD uint, selectCols ...string) (*UserOrder, error) {
	userOrderObj := &UserOrder{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `user_order` where `id`=? and `deleted_at` is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userOrderObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_order")
	}

	return userOrderObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserOrder) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserOrder) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_order provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userOrderColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userOrderInsertCacheMut.RLock()
	cache, cached := userOrderInsertCache[key]
	userOrderInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userOrderAllColumns,
			userOrderColumnsWithDefault,
			userOrderColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userOrderType, userOrderMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userOrderType, userOrderMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `user_order` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `user_order` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `user_order` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, userOrderPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_order")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == userOrderMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for user_order")
	}

CacheNoHooks:
	if !cached {
		userOrderInsertCacheMut.Lock()
		userOrderInsertCache[key] = cache
		userOrderInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single UserOrder record using the global executor.
// See Update for more documentation.
func (o *UserOrder) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the UserOrder.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserOrder) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userOrderUpdateCacheMut.RLock()
	cache, cached := userOrderUpdateCache[key]
	userOrderUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userOrderAllColumns,
			userOrderPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_order, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `user_order` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, userOrderPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userOrderType, userOrderMapping, append(wl, userOrderPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_order row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_order")
	}

	if !cached {
		userOrderUpdateCacheMut.Lock()
		userOrderUpdateCache[key] = cache
		userOrderUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q userOrderQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q userOrderQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_order")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_order")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserOrderSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserOrderSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userOrderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `user_order` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userOrderPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userOrder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userOrder")
	}
	return rowsAff, nil
}

// DeleteG deletes a single UserOrder record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserOrder) DeleteG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB(), hardDelete)
}

// Delete deletes a single UserOrder record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserOrder) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserOrder provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userOrderPrimaryKeyMapping)
		sql = "DELETE FROM `user_order` WHERE `id`=?"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE `user_order` SET %s WHERE `id`=?",
			strmangle.SetParamNames("`", "`", 0, wl),
		)
		valueMapping, err := queries.BindMapping(userOrderType, userOrderMapping, append(wl, userOrderPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_order")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_order")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q userOrderQuery) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAll deletes all matching rows.
func (q userOrderQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userOrderQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_order")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_order")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o UserOrderSlice) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserOrderSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userOrderBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userOrderPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM `user_order` WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userOrderPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userOrderPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE `user_order` SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userOrderPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("`", "`", 0, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userOrder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_order")
	}

	if len(userOrderAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserOrder) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no UserOrder provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserOrder) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserOrder(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserOrderSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty UserOrderSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserOrderSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserOrderSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userOrderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `user_order`.* FROM `user_order` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userOrderPrimaryKeyColumns, len(*o)) +
		"and `deleted_at` is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserOrderSlice")
	}

	*o = slice

	return nil
}

// UserOrderExistsG checks if the UserOrder row exists.
func UserOrderExistsG(ctx context.Context, iD uint) (bool, error) {
	return UserOrderExists(ctx, boil.GetContextDB(), iD)
}

// UserOrderExists checks if the UserOrder row exists.
func UserOrderExists(ctx context.Context, exec boil.ContextExecutor, iD uint) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `user_order` where `id`=? and `deleted_at` is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_order exists")
	}

	return exists, nil
}
