// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	ContentCategories string
	ContentChilds     string
	Contents          string
	UserOtps          string
	UserProfiles      string
	Users             string
}{
	ContentCategories: "content_categories",
	ContentChilds:     "content_childs",
	Contents:          "contents",
	UserOtps:          "user_otps",
	UserProfiles:      "user_profiles",
	Users:             "users",
}
